// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nhom4.Data;

#nullable disable

namespace nhom4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("nhom4.Models.DanhsachNCC", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mancc");

                    b.ToTable("DanhsachNCC");
                });

            modelBuilder.Entity("nhom4.Models.Danhsachkhachhang", b =>
                {
                    b.Property<string>("Makhachhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makhachhang");

                    b.ToTable("Danhsachkhachhang");
                });

            modelBuilder.Entity("nhom4.Models.Danhsachnhanvien", b =>
                {
                    b.Property<string>("Manhanvien")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tennhanvien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Manhanvien");

                    b.ToTable("Danhsachnhanvien");
                });
#pragma warning restore 612, 618
        }
    }
}
